// Auto-generated by scripts/generate-sponsors-list.js - run "npm run build" or "node scripts/generate-sponsors-list.js" to update
export const SPONSOR_IMAGES: { src: string; alt?: string; link?: string }[] = [
  {
    "src": "/images/sponsors/AWS%20GLOBAL.webp",
    "alt": "AWS",
    "link": "https://aws.amazon.com/f1/"
  },
  {
    "src": "/images/sponsors/Amex.webp",
    "alt": "American Express",
    "link": "https://www.americanexpress.com/"
  },
  {
    "src": "/images/sponsors/Paramount%2B.webp",
    "alt": "Paramount+",
    "link": "https://www.paramountplus.com/"
  },
  {
    "src": "/images/sponsors/TAGH_Shield_Monochrome_White-pw1.webp",
    "alt": "TAG Heuer",
    "link": "https://www.tagheuer.com/f1.html"
  },
  {
    "src": "/images/sponsors/TATA.webp",
    "alt": "TATA",
    "link": "https://www.tatacommunications.com/sports/powering-f1/"
  },
  {
    "src": "/images/sponsors/aggreko.webp",
    "alt": "Aggreko",
    "link": "https://www.aggreko.com/en-gb/sectors/events"
  },
  {
    "src": "/images/sponsors/allwyn.webp",
    "alt": "Allwyn",
    "link": "https://www.allwyn.com/"
  },
  {
    "src": "/images/sponsors/aramco.webp",
    "alt": "Aramco",
    "link": "https://www.saudiaramco.com/"
  },
  {
    "src": "/images/sponsors/barilla.webp",
    "alt": "Barilla",
    "link": "https://www.barillagroup.com/en/"
  },
  {
    "src": "/images/sponsors/crypto.com.webp",
    "alt": "Crypto.com",
    "link": "https://www.crypto.com"
  },
  {
    "src": "/images/sponsors/dhl.webp",
    "alt": "DHL",
    "link": "https://inmotion.dhl/en/formula-1/"
  },
  {
    "src": "/images/sponsors/globant.webp",
    "alt": "Globant",
    "link": "https://www.globant.com/"
  },
  {
    "src": "/images/sponsors/las%20vegas.webp",
    "alt": "Las Vegas",
    "link": "https://www.visitlasvegas.com/"
  },
  {
    "src": "/images/sponsors/lenovo.webp",
    "alt": "Lenovo",
    "link": "https://www.lenovo.com/"
  },
  {
    "src": "/images/sponsors/liqui-moly.webp",
    "alt": "Liqui Moly",
    "link": "https://www.liqui-moly.com/"
  },
  {
    "src": "/images/sponsors/louis%20vuitton.webp",
    "alt": "Louis Vuitton",
    "link": "https://www.louisvuitton.com/"
  },
  {
    "src": "/images/sponsors/lvmh.webp",
    "alt": "LVMH",
    "link": "https://www.lvmh.com/en"
  },
  {
    "src": "/images/sponsors/mcdonalds.webp",
    "alt": "McDonald's",
    "link": "https://www.arcosdorados.com/"
  },
  {
    "src": "/images/sponsors/moet%20hennessy.webp",
    "alt": "Moët Hennessy",
    "link": "https://www.lvmh.com/en/our-maisons/wines-spirits"
  },
  {
    "src": "/images/sponsors/msc.webp",
    "alt": "MSC",
    "link": "http://www.msccruises.com"
  },
  {
    "src": "/images/sponsors/nestle.webp",
    "alt": "Nestlé",
    "link": "https://www.nestle.com/brands/chocolate-confectionery/kitkat"
  },
  {
    "src": "/images/sponsors/pepsico.webp",
    "alt": "PepsiCo",
    "link": "https://www.pepsico.com/"
  },
  {
    "src": "/images/sponsors/pirelli.webp",
    "alt": "Pirelli",
    "link": "http://bit.ly/2IjWDjE"
  },
  {
    "src": "/images/sponsors/puma.webp",
    "alt": "Puma",
    "link": "https://go.puma.com/formula1-pp"
  },
  {
    "src": "/images/sponsors/pwc.webp",
    "alt": "PwC",
    "link": "https://www.pwc.com/us/en.html"
  },
  {
    "src": "/images/sponsors/qatar.webp",
    "alt": "Qatar Airways",
    "link": "https://www.qatarairways.com/en/offers/f1-fans-flight-deals.html"
  },
  {
    "src": "/images/sponsors/salesforce.webp",
    "alt": "Salesforce",
    "link": "https://www.salesforce.com/campaign/formula1/"
  },
  {
    "src": "/images/sponsors/santander.webp",
    "alt": "Santander",
    "link": "https://www.santander.com/"
  }
];
